services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: concert_zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000 # 클라이언트는 지정된 시간2마다 Zookeeper 서버에 하트비트를 전송,
    ports:
      - "22181:2181"
    networks:
      - concert_network

  broker:
    image: confluentinc/cp-kafka:latest
    container_name: concert_broker
    ports:
      - "9090:9090"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9090
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    #      KAFKA_CREATE_TOPICS: "concert.local.payment.topic:1:1"  # 토픽명:파티션수:복제수
    networks:
      - concert_network

networks:
  concert_network: