spring:
  config:
    activate:
      on-profile: local

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    #        generate_statistics: true
    #        session.events.log.LOG_QUERIES_SLOWER_THAN_MS: 300
    defer-datasource-initialization: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:concert;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;NON_KEYWORDS=USER
    username: sa
    password:

  data:
    redis:
      host: 127.0.0.1
      port: 6379

  h2:
    console:
      enabled: true

#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.orm.jdbc.bind: TRACE
#    org.hibernate.SQL_SLOW: INFO
#    org.hibernate.stat: DEBUG
#    org.springframework.orm: DEBUG
#    org.springframework.transaction: DEBUG

user-queue:
  max-waiting-number: 1000
  queue-token-expire-time: 10 # minute

kafka:
  bootstrapAddress: localhost:9090
  max:
    request:
      size: 3072000 # 3MB
  topics:
    concert:
      payment: concert.local.payment.topic
  groups:
    concert:
      payment: concert.local.payment.group
  consumer-cnt:
    concert:
      payment: 1