spring:
  config:
    activate:
      on-profile: mysql

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
        session.events.log.LOG_QUERIES_SLOWER_THAN_MS: 300
    defer-datasource-initialization: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/concert?rewriteBatchedStatements=true&profileSQL=true&logger=Slf4JLogger&maxQuerySizeToLog=999999
    username: root
    password: 1q2w3e4r1!

  data:
    redis:
      host: 127.0.0.1
      port: 6379

  h2:
    console:
      enabled: true

#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.orm.jdbc.bind: TRACE
#    org.hibernate.SQL_SLOW: INFO
#    org.hibernate.stat: DEBUG
#    org.springframework.orm: DEBUG
#    org.springframework.transaction: DEBUG

user-queue:
  max-waiting-number: 5
  queue-token-expire-time: 30 # minute
